# VacationPy
----

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from pprint import pprint

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame

In [2]:
file = "city_data.csv"
df = pd.read_csv(file)
df.dropna(inplace=True)
df.head()

,Unnamed: 0,City,Latitude,Longitude,Max Temperature,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,punta arenas,-53.15,-70.92,33.800,74,75,5.816044,CL,2020-07-16
1,1,port hedland,-20.32,118.57,53.600,71,0,8.052984,AU,2020-07-16
2,2,fukue,32.69,128.84,72.428,86,46,13.757181,JP,2020-07-16
3,3,okhotsk,59.38,143.30,56.426,89,100,6.710820,RU,2020-07-16
4,4,klaksvik,62.23,-6.59,51.800,93,0,14.987498,FO,2020-07-16

### Humidity Heatmap

In [3]:
gmaps.configure(api_key=g_key) #configure gmaps

In [4]:
locations = df[['Latitude','Longitude']] #use lat and long from df to create locations key
humidity = df['Humidity'] #define humidity to use as weight for heat map
max_humidity = max(humidity)
fig =gmaps.figure() #map of all cities in dataframe
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=max_humidity,point_radius=2)
fig.add_layer(heat_layer)#add heat map to cities in dataframe
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria

In [5]:
ideal_weather_df = df.loc[(df["Max Temperature"]>70)&(df["Max Temperature"]<80)&(df["Wind Speed"]<10)&(df["Cloudiness"]==0)]
ideal_weather_df.head(8)

,Unnamed: 0,City,Latitude,Longitude,Max Temperature,Humidity,Cloudiness,Wind Speed,Country,Date
9,10,korla,41.76,86.15,77.000,78,0,4.004123,CN,2020-07-16
112,122,phan thiet,10.93,108.10,77.270,85,0,4.250186,VN,2020-07-16
225,245,gondanglegi,-7.75,112.01,71.420,86,0,2.684328,ID,2020-07-16
303,328,bestobe,52.50,73.10,70.592,56,0,7.471380,KZ,2020-07-16
456,496,cavalcante,-13.80,-47.46,78.818,32,0,8.209570,BR,2020-07-16
458,499,batamshinskiy,50.56,58.27,77.000,29,0,8.947760,KZ,2020-07-16
491,534,demirci,39.05,28.66,73.994,43,0,8.992499,TR,2020-07-16
553,597,sorong,-0.88,131.25,77.936,82,0,3.690951,ID,2020-07-16

In [6]:
hotel,lat,long,city,country =[],[],[],[],[]

url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
for index, row  in ideal_weather_df.iterrows():
    params={"location": f"{row['Latitude']}, {row['Longitude']}","radius":5000, "type": "hotel", "key":g_key}
    
    try:
        response=requests.get(url,params=params).json()
        city.append(ideal_weather_df['City'][index])
        country.append(ideal_weather_df['Country'][index])
        hotel.append(response['results'][0]['name'])
        lat.append(response['results'][0]['geometry']['location']['lat'])
        long.append(response['results'][0]['geometry']['location']['lng'])
    except:
        print(f'There are no hotels nearby')
        city.append('NaN')
        country.append('NaN')
        hotel.append('NaN')
        lat.append(0)
        long.append(0)

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [7]:
hotel_df = pd.DataFrame(hotel)
hotel_df['City']=city
hotel_df['Latitude']=lat
hotel_df['Longitude']=long
hotel_df['Hotel Name']=hotel
hotel_df['Country']=country
hotel_df=hotel_df.loc[hotel_df['Hotel Name']!='NaN']
hotel_df.head(8)

,0,City,Latitude,Longitude,Hotel Name,Country
0,Bayingolin Mongol Autonomous Prefecture,korla,41.764115,86.145298,Bayingolin Mongol Autonomous Prefecture,CN
1,Phan Thiet,phan thiet,10.980460,108.261477,Phan Thiet,VN
2,Kediri,gondanglegi,-7.848016,112.017829,Kediri,ID
3,Bestobe,bestobe,52.501703,73.094719,Bestobe,KZ
4,Cavalcante,cavalcante,-13.798004,-47.457018,Cavalcante,BR
5,Badamsha,batamshinskiy,50.562393,58.278653,Badamsha,KZ
6,Demirci,demirci,39.047336,28.658544,Demirci,TR
7,Sorong,sorong,-0.876163,131.255828,Sorong,ID

In [8]:
# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

In [9]:
# Add marker layer on top of heat map
markers = gmaps.marker_layer(locations,info_box_content=hotel_info)
fig =gmaps.figure() 
fig.add_layer(heat_layer)
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))